robot:
  # Joint state controller publisher
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Controllers
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_tail
    pid: { p: 2.0, i: 0.01, d: 0.01 }
